pages:
  stage: deploy
  image: python:3.13
  tags:
    - shared-docker
  script:
    - pip install zensical mkdocstrings mkdocstrings-python
    - zensical build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main
